export const productos = [
  { id: 3, nombre: "Lechuga Manteca", categoria: "Verduras", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Lechuga Manteca" },
  { id: 4, nombre: "Lechuga Criolla", categoria: "Verduras", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Lechuga Criolla" },
  { id: 5, nombre: "Lechuga Repollada", categoria: "Verduras", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Lechuga Repollada" },
  { id: 6, nombre: "Lechuga Crespa", categoria: "Verduras", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Lechuga Crespa" },
  { id: 7, nombre: "Lechuga Morada", categoria: "Verduras", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Lechuga Morada" },
  { id: 8, nombre: "Navisa", categoria: "Verduras", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Navisa" },
  { id: 9, nombre: "Achicoria", categoria: "Verduras", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Achicoria" },
  { id: 10, nombre: "Acelga", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Acelga" },
  { id: 11, nombre: "Acelga Promo", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Acelga Promo" },
  { id: 12, nombre: "Espinaca", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Espinaca" },
  { id: 13, nombre: "Espinaca Promo", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Espinaca Promo" },
  { id: 14, nombre: "Brócoli", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Brócoli" },
  { id: 15, nombre: "Brócoli Promo", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Brócoli Promo" },
  { id: 16, nombre: "Coliflor", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Coliflor" },
  { id: 17, nombre: "Verdeo", categoria: "Verduras", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Verdeo" },
  { id: 18, nombre: "Verdeo Paq.", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Verdeo Paq." },
  { id: 19, nombre: "Puerro", categoria: "Verduras", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Puerro" },
  { id: 20, nombre: "Puerro Paq.", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Puerro Paq." },
  { id: 21, nombre: "Repollo colorado", categoria: "Verduras", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Repollo colorado" },
  { id: 22, nombre: "Repollo blanco", categoria: "Verduras", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Repollo blanco" },
  { id: 23, nombre: "Remolacha Paq.", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Remolacha Paq." },
  { id: 24, nombre: "Remolacha", categoria: "Verduras", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Remolacha" },
  { id: 25, nombre: "Rucula", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Rucula" },
  { id: 26, nombre: "Rucula Promo", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Rucula Promo" },
  { id: 27, nombre: "Corte", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Corte" },
  { id: 28, nombre: "Albahaca", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Albahaca" },
  { id: 29, nombre: "Apio", categoria: "Verduras", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Apio" },
  { id: 30, nombre: "Perejil Paq.", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Perejil Paq." },
  { id: 31, nombre: "Hinojo", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Hinojo" },
  { id: 32, nombre: "Rabanito Paq.", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Rabanito Paq." },
  { id: 33, nombre: "Verdura P/Sopa", categoria: "Verduras", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Verdura P/Sopa" },
  { id: 34, nombre: "Kale Paq.", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Kale Paq." },
  { id: 35, nombre: "Menta Paq.", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Menta Paq." },
  { id: 36, nombre: "Cilantro Paq.", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Cilantro Paq." },
  { id: 37, nombre: "Ciboulette Paq.", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Ciboulette Paq." },
  { id: 38, nombre: "Berro Paq.", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Berro Paq." },
  { id: 39, nombre: "Acusay Paq.", categoria: "Verduras", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Acusay Paq." },
  { id: 40, nombre: "Papa Lavada", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Papa Lavada" },
  { id: 41, nombre: "Papa Sucia", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Papa Sucia" },
  { id: 42, nombre: "Cebolla", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Cebolla" },
  { id: 43, nombre: "Cebolla Color", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Cebolla Color" },
  { id: 44, nombre: "Zanahoria", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Zanahoria" },
  { id: 45, nombre: "Zapallo Anco", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Zapallo Anco" },
  { id: 46, nombre: "Zapallo Coquena", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Zapallo Coquena" },
  { id: 47, nombre: "Zapallo Cabuci", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Zapallo Cabuci" },
  { id: 48, nombre: "Batata", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Batata" },
  { id: 49, nombre: "Bognato", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Bognato" },
  { id: 50, nombre: "Mandioca", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Mandioca" },
  { id: 51, nombre: "Ajo chico", categoria: "Hortalizas", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Ajo chico" },
  { id: 52, nombre: "Ajo grande", categoria: "Hortalizas", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Ajo grande" },
  { id: 53, nombre: "Tomate Redondo", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Tomate Redondo" },
  { id: 54, nombre: "Tomate Perita", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Tomate Perita" },
  { id: 55, nombre: "Tomate en Rama", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Tomate en Rama" },
  { id: 56, nombre: "Tomate Cherry", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Tomate Cherry" },
  { id: 57, nombre: "Morrón Rojo", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Morrón Rojo" },
  { id: 58, nombre: "Morrón Verde", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Morrón Verde" },
  { id: 59, nombre: "Morrón Amarillo", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Morrón Amarillo" },
  { id: 60, nombre: "Berenjena", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Berenjena" },
  { id: 61, nombre: "Zapallito Redondo", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Zapallito Redondo" },
  { id: 62, nombre: "Zapallito Largo", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Zapallito Largo" },
  { id: 63, nombre: "Pepino", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Pepino" },
  { id: 64, nombre: "Choclo", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Choclo" },
  { id: 65, nombre: "Chaucha Ancha", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Chaucha Ancha" },
  { id: 66, nombre: "Chaucha Fina", categoria: "Hortalizas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Chaucha Fina" },
  { id: 67, nombre: "Naranja Jugo", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Naranja Jugo" },
  { id: 68, nombre: "Naranja Ombligo", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Naranja Ombligo" },
  { id: 69, nombre: "Mandarina Encore", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Mandarina Encore" },
  { id: 70, nombre: "Mandarina Murco Grande", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Mandarina Murco Grande" },
  { id: 71, nombre: "Mandarina Criolla", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Mandarina Criolla" },
  { id: 72, nombre: "Mandarina Elendale", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Mandarina Elendale" },
  { id: 73, nombre: "Quinoto", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Quinoto" },
  { id: 74, nombre: "Limón", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Limón" },
  { id: 75, nombre: "Pomelo Rojo", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Pomelo Rojo" },
  { id: 76, nombre: "Pomelo Blanco", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Pomelo Blanco" },
  { id: 77, nombre: "Manzana Roja Chica", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Manzana Roja Chica" },
  { id: 78, nombre: "Manzana Roja Grande", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Manzana Roja Grande" },
  { id: 79, nombre: "Manzana Pink Lady", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Manzana Pink Lady" },
  { id: 80, nombre: "Manzana Roja Premium", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Manzana Roja Premium" },
  { id: 81, nombre: "Manzana Verde", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Manzana Verde" },
  { id: 82, nombre: "Pera", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Pera" },
  { id: 83, nombre: "Pera Premium", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Pera Premium" },
  { id: 84, nombre: "Banana Brasil", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Banana Brasil" },
  { id: 85, nombre: "Banana Bolivia", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Banana Bolivia" },
  { id: 86, nombre: "Banana Ecuador", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Banana Ecuador" },
  { id: 87, nombre: "Kiwi Chico", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Kiwi Chico" },
  { id: 88, nombre: "Kiwi Grande", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Kiwi Grande" },
  { id: 89, nombre: "Palta Hass Chica", categoria: "Frutas", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Palta Hass Chica" },
  { id: 90, nombre: "Paltas Hass Grande", categoria: "Frutas", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Paltas Hass Grande" },
  { id: 91, nombre: "Lima", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Lima" },
  { id: 92, nombre: "Jengibre", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Jengibre" },
  { id: 93, nombre: "Cúrcuma Fresca", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Cúrcuma Fresca" },
  { id: 94, nombre: "Picante", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Picante" },
  { id: 95, nombre: "Mango", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Mango" },
  { id: 96, nombre: "Uva Negra", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Uva Negra" },
  { id: 97, nombre: "Uva Roja", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Uva Roja" },
  { id: 98, nombre: "Uva Verde", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Uva Verde" },
  { id: 99, nombre: "Piña", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Piña" },
  { id: 100, nombre: "Sandía", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Sandía" },
  { id: 101, nombre: "Repollos Bruselas", categoria: "Frutas", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Repollos Bruselas" },
  { id: 102, nombre: "Espárragos", categoria: "Frutas", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Espárragos" },
  { id: 103, nombre: "Arvejas", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Arvejas" },
  { id: 104, nombre: "Alcachofa", categoria: "Frutas", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Alcachofa" },
  { id: 105, nombre: "Frutilla", categoria: "Frutas", precio: 0, unidad: "kg", tipo: "Peso", descripcion: "Frutilla" },
  { id: 106, nombre: "Arándanos", categoria: "Frutas", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Arándanos" },
  { id: 107, nombre: "Maple Huevo Color", categoria: "Huevos", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Maple Huevo Color" },
  { id: 108, nombre: "Maple Huevo Blanco", categoria: "Huevos", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Maple Huevo Blanco" },
  { id: 109, nombre: "1/2 Docena Color", categoria: "Huevos", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "1/2 Docena Color" },
  { id: 110, nombre: "1/2 Docena Blanco", categoria: "Huevos", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "1/2 Docena Blanco" },
  { id: 111, nombre: "Bandeja Sopa", categoria: "Preparados", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Bandeja Sopa" },
  { id: 112, nombre: "Bandeja Ensalada", categoria: "Preparados", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Bandeja Ensalada" },
  { id: 113, nombre: "Bandeja Champ. Blanco", categoria: "Preparados", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Bandeja Champ. Blanco" },
  { id: 114, nombre: "Bandeja Champ. Porto", categoria: "Preparados", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Bandeja Champ. Porto" },
  { id: 115, nombre: "Bandeja Rúcula y Cherry", categoria: "Preparados", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Bandeja Rúcula y Cherry" },
  { id: 116, nombre: "Bandeja Brotes de Soja", categoria: "Preparados", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Bandeja Brotes de Soja" },
  { id: 117, nombre: "Bolsa Carbón", categoria: "Otros", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Bolsa Carbón" },
  { id: 118, nombre: "Bolsa Leña", categoria: "Otros", precio: 0, unidad: "unidad", tipo: "Unidad", descripcion: "Bolsa Leña" },
];
